# Generated by Django 3.2.15 on 2022-11-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20220824_0210'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='空欄の場合は、対象校名と種別を組み合わせて表示します', max_length=50, null=True, unique=True, verbose_name='企画名')),
                ('type', models.CharField(choices=[('オンライン', 'オンライン'), ('ハイブリッド', 'ハイブリッド'), ('出張', '出張'), ('ツアー', 'ツアー')], max_length=6, verbose_name='種別')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('venue', models.CharField(blank=True, max_length=80, null=True, verbose_name='場所')),
                ('status', models.CharField(choices=[('参加者募集中', '参加者募集中'), ('参加者打診中', '参加者打診中'), ('参加者決定済み', '参加者決定済み'), ('企画終了', '企画終了'), ('アーカイブ', 'アーカイブ')], default='参加者募集中', max_length=10, verbose_name='状態')),
                ('admin', models.ManyToManyField(blank=True, help_text='プラットフォーム上において、企画ページの編集権限を持つユーザーです', related_name='event_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
                ('group_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group', verbose_name='担当班')),
                ('person_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='統括')),
                ('school', models.ManyToManyField(related_name='event', to='schools.School', verbose_name='対象校')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from_participant', models.TextField(blank=True, help_text='作成メンバーに伝えたいことを入力してください', max_length=1000, null=True, verbose_name='参加者からのメッセージ')),
                ('message_from_admin', models.TextField(blank=True, help_text='参加者に伝えたいことを入力してください', max_length=1000, null=True, verbose_name='作成の打診担当者からのメッセージ')),
                ('status', models.CharField(choices=[('回答待ち', '回答待ち'), ('参加', '参加'), ('辞退', '辞退')], default='回答待ち', max_length=4, verbose_name='打診の状態')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='events.event', verbose_name='イベント')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
            ],
            options={
                'verbose_name': 'イベント参加者',
                'verbose_name_plural': 'イベント参加者',
            },
        ),
    ]
