# Generated by Django 3.2.15 on 2022-08-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220828_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooldetail',
            options={'verbose_name': '学校詳細', 'verbose_name_plural': '学校詳細'},
        ),
    ]
