# Generated by Django 3.2.15 on 2022-08-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_schooldetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='school',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail', serialize=False, to='events.school', verbose_name='学校'),
        ),
    ]
