# Generated by Django 3.2.15 on 2022-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_schooldetail_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='number',
            field=models.IntegerField(default=0, verbose_name='管理用連番'),
        ),
    ]
