# Generated by Django 3.2.15 on 2022-08-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220824_0210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_school_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('オンライン', 'オンライン'), ('ハイブリッド', 'ハイブリッド'), ('出張', '出張'), ('ツアー', 'ツアー')], max_length=6, verbose_name='種別')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('is_event_by_volunteers', models.BooleanField(default=False, verbose_name='個人企画')),
                ('admin', models.ManyToManyField(blank=True, related_name='event_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
                ('group_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group', verbose_name='担当班')),
                ('participants', models.ManyToManyField(related_name='event_participate_in', to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
                ('person_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='統括')),
                ('school', models.ManyToManyField(related_name='event', to='events.School', verbose_name='対象校')),
            ],
        ),
    ]
