# Generated by Django 3.2.15 on 2022-08-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント'},
        ),
    ]
