# Generated by Django 3.2.15 on 2022-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='空欄の場合は、対象校名と種別を組み合わせて表示します', max_length=50, null=True, unique=True, verbose_name='企画名'),
        ),
    ]
