# Generated by Django 3.2.15 on 2022-08-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220824_0210'),
        ('events', '0011_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group', verbose_name='担当班'),
        ),
    ]
