# Generated by Django 3.2.15 on 2022-09-01 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220901_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
            preserve_default=False,
        ),
    ]
