# Generated by Django 3.2.15 on 2022-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_is_event_by_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('参加者募集中', '参加者募集中'), ('参加者打診中', '参加者打診中'), ('参加者決定済み', '参加者決定済み'), ('企画終了', '企画終了'), ('アーカイブ', 'アーカイブ')], default='参加者募集中', max_length=10, verbose_name='状態'),
        ),
    ]
