# Generated by Django 3.2.15 on 2022-10-24 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_auto_20221024_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='event',
            name='admin',
            field=models.ManyToManyField(blank=True, help_text='プラットフォーム上において、企画ページの編集権限を持つユーザーです', related_name='event_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
