# Generated by Django 3.2.15 on 2022-10-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_auto_20221024_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from_participant', models.TextField(help_text='作成メンバーに伝えたいことを入力してください', max_length=1000, verbose_name='参加者からのメッセージ')),
                ('message_from_admin', models.TextField(help_text='参加者に伝えたいことを入力してください', max_length=1000, verbose_name='作成の打診担当者からのメッセージ')),
                ('status', models.CharField(choices=[('回答待ち', '回答待ち'), ('参加', '参加'), ('辞退', '辞退')], default='回答待ち', max_length=4, verbose_name='打診の状態')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='events.event', verbose_name='イベント')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
            ],
            options={
                'verbose_name': 'イベント参加者',
                'verbose_name_plural': 'イベント参加者',
            },
        ),
    ]
