# Generated by Django 3.2.15 on 2022-10-24 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_eventparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants_declined',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants_invited',
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(help_text='打診が終了し、企画への参加が決定したメンバーを選択します', related_name='event_participate_in', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
