# Generated by Django 3.2.15 on 2022-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20221024_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='message_from_admin',
            field=models.TextField(blank=True, help_text='参加者に伝えたいことを入力してください', max_length=1000, null=True, verbose_name='作成の打診担当者からのメッセージ'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='message_from_participant',
            field=models.TextField(blank=True, help_text='作成メンバーに伝えたいことを入力してください', max_length=1000, null=True, verbose_name='参加者からのメッセージ'),
        ),
    ]
