# Generated by Django 3.2.15 on 2022-11-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日時'),
        ),
    ]
