# Generated by Django 3.2.16 on 2022-12-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_calendar', '0003_auto_20221208_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='開始時刻'),
        ),
    ]
