# Generated by Django 3.2.16 on 2022-12-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_calendar', '0004_auto_20221210_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='場所'),
        ),
    ]
