# Generated by Django 3.2.16 on 2022-12-11 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fw_calendar', '0006_auto_20221210_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='paritipants',
            field=models.ManyToManyField(blank=True, related_name='participating_schedules', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
