# Generated by Django 3.2.16 on 2022-12-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_calendar', '0007_schedule_paritipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='model_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='モデルのpk'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='model_type',
            field=models.CharField(blank=True, choices=[('event', '企画')], max_length=20, verbose_name='モデルの種類'),
        ),
    ]
