# Generated by Django 3.2.16 on 2022-12-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fw_calendar', '0008_auto_20221211_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='paritipants',
            new_name='participants',
        ),
    ]
