# Generated by Django 3.2.16 on 2022-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_calendar', '0009_rename_paritipants_schedule_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
