# Generated by Django 3.2.16 on 2022-12-07 04:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='請求書番号')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='発行回数')),
                ('post', models.CharField(default='担当者', max_length=10, verbose_name='FairWindの担当者の役職')),
                ('issued_date', models.DateField(default=datetime.date.today, verbose_name='発行日')),
                ('payment_deadline', models.DateField(blank=True, default=None, verbose_name='支払い期限')),
                ('display_bank_account', models.BooleanField(default=True, verbose_name='団体口座を表示')),
                ('is_archived', models.BooleanField(default=False, verbose_name='アーカイブ済み')),
                ('is_issued', models.BooleanField(default=False, verbose_name='発行済み')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='events.event', verbose_name='企画')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='FairWindの担当者')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='schools.school', verbose_name='宛先')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('item', models.CharField(max_length=11, verbose_name='費目')),
                ('breakdown', models.CharField(blank=True, max_length=20, null=True, verbose_name='内訳')),
                ('volume', models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='個', max_length=4, verbose_name='単位')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_item', to='events_accounting.bill', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求項目',
                'verbose_name_plural': '請求項目',
            },
        ),
    ]
