# Generated by Django 3.2.15 on 2022-11-19 02:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_alter_school_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='件名')),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='請求書番号')),
                ('post', models.CharField(default='担当者', max_length=10, verbose_name='FairWindの担当者の役職')),
                ('issued_date', models.DateField(default=datetime.date.today, verbose_name='請求日')),
                ('payment_deadline', models.DateField(default=datetime.date.today, verbose_name='支払い期限')),
                ('display_bank_account', models.BooleanField(default=True, verbose_name='団体口座を表示')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='events.event', verbose_name='企画')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='FairWindの担当者')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='schools.school', verbose_name='宛先')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
            },
        ),
    ]
