# Generated by Django 3.2.15 on 2022-11-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_deadline',
        ),
    ]
