# Generated by Django 3.2.15 on 2022-11-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0002_remove_bill_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_deadline',
            field=models.DateField(blank=True, default=None, verbose_name='支払い期限'),
        ),
    ]
