# Generated by Django 3.2.15 on 2022-11-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0004_alter_bill_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='発行回数'),
        ),
    ]
