# Generated by Django 3.2.15 on 2022-11-19 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0005_bill_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('item', models.CharField(max_length=100, verbose_name='費目')),
                ('breakdown', models.CharField(blank=True, max_length=100, null=True, verbose_name='内訳')),
                ('volume', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='個', max_length=10, verbose_name='単位')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_item', to='events_accounting.bill', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求項目',
                'verbose_name_plural': '請求項目',
            },
        ),
    ]
