# Generated by Django 3.2.15 on 2022-11-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_memo'),
        ('events_accounting', '0007_alter_bill_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='schools.school', verbose_name='宛先'),
        ),
    ]
