# Generated by Django 3.2.15 on 2022-11-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('events_accounting', '0008_alter_bill_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='請求書番号'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='events.event', verbose_name='企画'),
        ),
    ]
