# Generated by Django 3.2.15 on 2022-11-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0009_auto_20221119_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='請求書番号'),
        ),
    ]
