# Generated by Django 3.2.15 on 2022-11-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0010_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='has_archived',
            field=models.BooleanField(default=False, verbose_name='アーカイブ済み'),
        ),
    ]
