# Generated by Django 3.2.15 on 2022-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0014_alter_bill_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='発行済み'),
        ),
    ]
