# Generated by Django 3.2.15 on 2022-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0015_bill_is_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='volume',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='数量'),
        ),
    ]
