# Generated by Django 3.2.15 on 2022-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_accounting', '0016_alter_billingitem_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='breakdown',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='内訳'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='item',
            field=models.CharField(max_length=11, verbose_name='費目'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='unit',
            field=models.CharField(default='個', max_length=4, verbose_name='単位'),
        ),
    ]
