# Generated by Django 3.2.16 on 2022-12-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0003_alter_school_memo'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=50, null=True, verbose_name='相手')),
                ('event', models.OneToOneField(blank=True, help_text='企画ページに連絡共有を表示する場合は、企画を選択してください。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='events.event', verbose_name='企画')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='schools.school', verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='ContactItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=50, null=True, verbose_name='概要')),
                ('text', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(verbose_name='日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contact.contact', verbose_name='連絡')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contactitems', verbose_name='親コメント')),
                ('person_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_items', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
        ),
    ]
