# Generated by Django 3.2.16 on 2022-12-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100, verbose_name='相手')),
                ('event', models.ForeignKey(blank=True, help_text='企画ページに連絡共有を表示する場合は、企画を選択してください。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='events.event', verbose_name='企画')),
            ],
            options={
                'verbose_name': '連絡',
                'verbose_name_plural': '連絡',
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='送信者')),
                ('recipient', models.CharField(max_length=50, verbose_name='受信者')),
                ('date', models.DateField(verbose_name='日時')),
                ('summary', models.TextField(blank=True, help_text='Markdown形式を使うことができます。', max_length=250, null=True, verbose_name='要約')),
                ('text', models.TextField(verbose_name='内容')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contact.contact', verbose_name='連絡')),
                ('person_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_items', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '連絡メッセージ',
                'verbose_name_plural': '連絡メッセージ',
            },
        ),
    ]
