# Generated by Django 3.2.16 on 2022-12-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '連絡', 'verbose_name_plural': '連絡'},
        ),
        migrations.AlterModelOptions(
            name='contactitems',
            options={'verbose_name': '連絡メッセージ', 'verbose_name_plural': '連絡メッセージ'},
        ),
        migrations.AlterField(
            model_name='contactitems',
            name='date',
            field=models.DateField(verbose_name='日時'),
        ),
    ]
