# Generated by Django 3.2.16 on 2022-12-14 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_alter_contactitems_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='送信者')),
                ('recipient', models.CharField(max_length=50, verbose_name='受信者')),
                ('date', models.DateField(verbose_name='日時')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='要約')),
                ('text', models.TextField(verbose_name='内容')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contact.contact', verbose_name='連絡')),
                ('person_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_items', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '連絡メッセージ',
                'verbose_name_plural': '連絡メッセージ',
            },
        ),
        migrations.DeleteModel(
            name='ContactItems',
        ),
    ]
