# Generated by Django 3.2.16 on 2022-12-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20221214_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='school',
        ),
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.CharField(default='長崎西', max_length=100, verbose_name='相手'),
            preserve_default=False,
        ),
    ]
