# Generated by Django 3.2.16 on 2022-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20221214_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='要約'),
        ),
    ]
