# Generated by Django 3.2.16 on 2022-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactitem_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='summary',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='要約'),
        ),
    ]
