# Generated by Django 3.2.16 on 2022-12-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('contact', '0008_alter_contactitem_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='event',
            field=models.ForeignKey(blank=True, help_text='企画ページに連絡共有を表示する場合は、企画を選択してください。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='events.event', verbose_name='企画'),
        ),
    ]
