# Generated by Django 3.2.16 on 2022-12-08 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220824_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='カレンダーUUID'),
        ),
    ]
