# Generated by Django 3.2.15 on 2022-11-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='title',
        ),
    ]
