# Generated by Django 3.2.16 on 2022-12-07 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('◎', '◎'), ('○', '○'), ('△', '△'), ('×', '×')], max_length=15, verbose_name='出欠')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='コメント')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='events.event', verbose_name='企画')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
            options={
                'verbose_name': '出欠情報',
                'verbose_name_plural': '出欠情報',
            },
        ),
    ]
