# Generated by Django 3.2.15 on 2022-11-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('events_recruitment', '0002_alter_eventrecruitment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrecruitment',
            options={'verbose_name': '出欠情報', 'verbose_name_plural': '出欠情報'},
        ),
        migrations.AlterField(
            model_name='eventrecruitment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='events.event', verbose_name='企画'),
        ),
        migrations.AlterField(
            model_name='eventrecruitment',
            name='preference',
            field=models.CharField(choices=[('◎', '◎'), ('○', '○'), ('△', '△'), ('×', '×')], max_length=15, verbose_name='出欠'),
        ),
    ]
