# Generated by Django 3.2.15 on 2022-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20221115_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
    ]
