# Generated by Django 3.2.16 on 2022-12-06 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReflectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_template', to='events.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': '振り返りテンプレート',
                'verbose_name_plural': '振り返りテンプレート',
            },
        ),
        migrations.CreateModel(
            name='EventReflectionGeneral',
            fields=[
                ('eventreflectiontemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_reflection.eventreflectiontemplate')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '全体振り返り',
                'verbose_name_plural': '全体振り返り',
            },
            bases=('events_reflection.eventreflectiontemplate',),
        ),
        migrations.CreateModel(
            name='EventReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='events.event', verbose_name='イベント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '振り返り',
                'verbose_name_plural': '振り返り',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
