# Generated by Django 3.2.16 on 2022-12-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('events_reflection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreflection',
            name='reflection',
            field=models.TextField(blank=True, null=True, verbose_name='振り返り'),
        ),
        migrations.CreateModel(
            name='EventReflectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_template', to='events.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': '振り返りテンプレート',
                'verbose_name_plural': '振り返りテンプレート',
            },
        ),
        migrations.CreateModel(
            name='EventReflectionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_general', to='events.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': '全体振り返り',
                'verbose_name_plural': '全体振り返り',
            },
        ),
    ]
