# Generated by Django 3.2.16 on 2022-12-05 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_reflection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreflection',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='events.event', verbose_name='イベント'),
        ),
        migrations.AlterField(
            model_name='eventreflection',
            name='reflection',
            field=models.TextField(blank=True, null=True, verbose_name='振り返り'),
        ),
        migrations.AlterField(
            model_name='eventreflection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
