# Generated by Django 3.2.16 on 2022-12-05 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_reflection', '0002_auto_20221205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreflection',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='events.event', verbose_name='イベント'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventreflection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='accounts.user', verbose_name='ユーザー'),
            preserve_default=False,
        ),
    ]
