# Generated by Django 3.2.16 on 2022-12-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('events_reflection', '0003_auto_20221205_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReflectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_template', to='events.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': '振り返りテンプレート',
                'verbose_name_plural': '振り返りテンプレート',
            },
        ),
        migrations.CreateModel(
            name='EventReflectionGeneral',
            fields=[
                ('eventreflectiontemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_reflection.eventreflectiontemplate')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '全体振り返り',
                'verbose_name_plural': '全体振り返り',
            },
            bases=('events_reflection.eventreflectiontemplate',),
        ),
    ]
